version: "3.8"
services:
  marine_traffic:
    container_name: marine_traffic
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - marine_traffic
    environment:
      NGINX_FPM_HOST: marine_traffic
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  db:
    container_name: db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3310:3310
    environment:
      MYSQL_DATABASE: marine_traffic
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge